=== sioudhung/study/JessMA-master/support files/xsd/mvc-config-main-3.3.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://www.jessma.org" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" targetNamespace="http://www.jessma.org">
	<xs:element name="MVC-MAIN">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" minOccurs="0" name="global">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="1" minOccurs="0" name="encoding">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="UTF-8"></xs:enumeration>
										<xs:enumeration value="GB2312"></xs:enumeration>
										<xs:enumeration value="GB18030"></xs:enumeration>
										<xs:enumeration value="GBK"></xs:enumeration>
										<xs:enumeration value="BIG5"></xs:enumeration>
										<xs:enumeration value="UTF-16"></xs:enumeration>
										<xs:enumeration value="UTF-16BE"></xs:enumeration>
										<xs:enumeration value="UTF-16LE"></xs:enumeration>
										<xs:enumeration value="ISO-8859-1"></xs:enumeration>
										<xs:enumeration value="US-ASCII"></xs:enumeration>
										<xs:enumeration value=""></xs:enumeration>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element maxOccurs="1" minOccurs="0" name="action-suffix">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="((\.)?([a-zA-Z0-9])+)?"></xs:pattern>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="base-path" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="type" default="auto">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="auto"></xs:enumeration>
														<xs:enumeration value="manual"></xs:enumeration>
														<xs:enumeration value="none"></xs:enumeration>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="href">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:pattern value="http(s)?\:\/\/(\w)+.*"></xs:pattern>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="i18n" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="default-locale" default="zh_CN">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="([a-z]{2}(_[A-Z]{2})?)?"></xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="default-bundle" default="res.application-message">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="((\w+((\-|\_)?\w+)*)(\.\w+((\-|\_)?\w+)*)*)?"></xs:pattern>

											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="bean-validation" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="enable" default="true">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="4"></xs:minLength>
												<xs:maxLength value="5"></xs:maxLength>
												<xs:enumeration value="true"></xs:enumeration>
												<xs:enumeration value="false"></xs:enumeration>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
                                    <xs:attribute name="bundle" default="res.validation-message">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="((\w+((\-|\_)?\w+)*)(\.\w+((\-|\_)?\w+)*)*)?"></xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
                                    <xs:attribute name="validator" default="org.jessma.mvc.validation.HibernateBeanValidator">
										<xs:simpleType>
											<xs:restriction base="xs:string">

												<xs:pattern value="([a-z]\w*(\.([a-z]\w*))*\.[A-Z]\w*)?"></xs:pattern>
											</xs:restriction>
										</xs:simpleType>
                                    </xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="action-convention" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:sequence></xs:sequence>
									<xs:attribute name="enable" default="true">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true"></xs:enumeration>
												<xs:enumeration value="false"></xs:enumeration>
												<xs:minLength value="4"></xs:minLength>
												<xs:maxLength value="5"></xs:maxLength>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="detect-physical-file" default="true">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true"></xs:enumeration>
												<xs:enumeration value="false"></xs:enumeration>
												<xs:minLength value="4"></xs:minLength>
												<xs:maxLength value="5"></xs:maxLength>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="action-base-package" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="([a-z]\w*)*(\.([a-z]\w*))*"></xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="dispatch-file-path" default="/WEB-INF/page">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern
													value="(/((\w+([-/.])?)*\w+/?)?)?|/?(((\$\{)(\w+([-.])?)*\w+)+\})?/?">
												</xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="dispatch-file-type" default="jsp">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"></xs:minLength>
												<xs:pattern value="((\.)|(\*\.))?\w+"></xs:pattern>
												<xs:enumeration value="jsp"></xs:enumeration>
												<xs:enumeration value="ftl"></xs:enumeration>
												<xs:enumeration value="vm"></xs:enumeration>
												<xs:enumeration value="html"></xs:enumeration>
												<xs:enumeration value="htm"></xs:enumeration>
												<xs:maxLength value="10"></xs:maxLength>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="physical-file-path">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern
													value="(/((\w+([-/.])?)*\w+/?)?)?|/?(((\$\{)(\w+([-.])?)*\w+)+\})?/?">
												</xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="file-name-separator" default="_">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:length value="1"></xs:length>
												<xs:enumeration value="_"></xs:enumeration>
												<xs:enumeration value="-"></xs:enumeration>
												<xs:enumeration value="@"></xs:enumeration>
												<xs:enumeration value="#"></xs:enumeration>
												<xs:enumeration value="%"></xs:enumeration>
												<xs:enumeration value="^"></xs:enumeration>
												<xs:enumeration value="&amp;"></xs:enumeration>
												<xs:enumeration value="."></xs:enumeration>
												<xs:enumeration value="~"></xs:enumeration>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="action-filters" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="filter" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="class" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"></xs:minLength>
															<xs:pattern value="[a-z]\w*(\.([a-z]\w*))*\.[A-Z]\w*">
															</xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="pattern" use="optional" default=".*">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"></xs:minLength>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="methods" default=".*">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"></xs:minLength>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="result-path-aliases" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="alias" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"></xs:minLength>
															<xs:pattern value="(\w+[-|_]?)*\w+"></xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="path" type="xs:string" use="required"></xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="global-results" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="result" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="name" default="$0">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:pattern value="(\$|\#|\-|\_|\.|\w)+">
																	</xs:pattern>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="type" default="dispatch">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="dispatch"></xs:enumeration>
																	<xs:enumeration value="redirect"></xs:enumeration>
																	<xs:enumeration value="chain"></xs:enumeration>
																	<xs:enumeration value="finish"></xs:enumeration>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="global-exception-mappings" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="exception-mapping" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="exception" default="java.lang.Exception">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"></xs:minLength>
															<xs:pattern value="[a-z]\w*(\.([a-z]\w*))*\.[A-Z]\w*">
															</xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="result" default="exception">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="(\$|\#|\-|\_|\.|\w)+"></xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="include">
					<xs:complexType>
						<xs:attribute name="file" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="5" />
									<xs:pattern value=".+\w\.xml"></xs:pattern>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="actions">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="action">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="entry" maxOccurs="unbounded"
											minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" minOccurs="0"
														name="result">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="name" default="success">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:pattern value="(\$|\#|\-|\_|\.|\w)+">
																				</xs:pattern>
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																	<xs:attribute name="type" default="dispatch">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:enumeration value="dispatch" />
																				<xs:enumeration value="redirect" />
																				<xs:enumeration value="chain" />
																				<xs:enumeration value="finish">
																				</xs:enumeration>
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="exception-mapping" maxOccurs="unbounded"
														minOccurs="0">
														<xs:complexType>
															<xs:attribute name="exception" default="java.lang.Exception">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1">
																		</xs:minLength>
																		<xs:pattern value="[a-z]\w*(\.([a-z]\w*))*\.[A-Z]\w*">
																		</xs:pattern>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="result" default="exception">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:pattern value="(\$|\#|\-|\_|\.|\w)+">
																		</xs:pattern>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" use="optional">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="0">
															</xs:minLength>
															<xs:pattern value="(\w+([-_.])?)*\w*">
															</xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="method">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1">
															</xs:minLength>
															<xs:pattern value="[a-z_$]+([\w_$])*">
															</xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element maxOccurs="unbounded" minOccurs="0"
											name="result">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="name" default="success">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:pattern value="(\$|\#|\-|\_|\.|\w)+">
																	</xs:pattern>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="type" default="dispatch">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="dispatch" />
																	<xs:enumeration value="redirect" />
																	<xs:enumeration value="chain" />
																	<xs:enumeration value="finish">
																	</xs:enumeration>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="exception-mapping" maxOccurs="unbounded"
											minOccurs="0">
											<xs:complexType>
												<xs:attribute name="exception" default="java.lang.Exception">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1">
															</xs:minLength>
															<xs:pattern value="[a-z]\w*(\.([a-z]\w*))*\.[A-Z]\w*">
															</xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="result" default="exception">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="(\$|\#|\-|\_|\.|\w)+">
															</xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1" />
												<xs:pattern value="(\w+([-_.])?)*\w+"></xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="class">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1"></xs:minLength>
												<xs:pattern value="[a-z]\w*(\.([a-z]\w*))*\.[A-Z]\w*"></xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="path" default="/">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="(/((\w+([-/.])?)*\w+/?)?)?">
									</xs:pattern>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== sioudhung/study/JessMA-master/support files/conf/mvc-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<MVC-MAIN	xmlns="http://www.jessma.org"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://www.jessma.org http://www.jessma.org/schema/mvc-config-main-3.3.xsd">
	<global>
		<!-- request 和 response 的默认编码（可选，默认：不设置） -->
		<encoding>UTF-8</encoding>
		<!-- Action 请求的后缀（可选，默认：.action） -->
		<action-suffix>.action</action-suffix>
		<!-- 页面的  ${__base}  变量设置（可选，默认：type = 'auto', href = ''） -->
		<base-path type="auto"/>

		<!--
			default-locale	：应用程序默认语言选项（默认：与当前操作系统一致）
			default-bundle	：应用程序默认 Bundle（默认：res.application-message）
		-->
		<i18n default-locale="" default-bundle="" />
		
		<!--
			enable		：是否开启 Bean Validation 机制（默认：开启）
			bundle		：验证文本消息的 Bundle（默认：res.validation-message）
			validator	：验证器类（默认：org.jessma.mvc.validation.HibernateBeanValidator）
		-->
		<bean-validation
			enable="true"
			bundle=""
			validator=""
		/>

		<!-- Action Convention 配置
			enable					：是否启用 Action Convention 功能（默认：true）
			detect-physical-file	：是否检查 Action Result 物理视图文件的确存在（默认：true）
			action-base-package		：Action 类的基包（默认：""）
			dispatch-file-path		：转发视图的基路径（默认："/WEB-INF/page"）
			dispatch-file-type		：转发视图的类型（默认："jsp"）
			physical-file-path		：物理视图文件的基路径（默认：""，与 'dispatch-file-path' 一致）
			file-name-separator		：视图名称分隔符（默认："_"）
		-->
		<action-convention
			enable="true"
			detect-physical-file="true"
			action-base-package="action"
			dispatch-file-path="${jsp-base}"
			dispatch-file-type="jsp"
			physical-file-path=""
			file-name-separator="_"
		/>
		
		<action-filters>
		<!--  
			<filter pattern="action.*" class="global.MyActionFilter1"/>
			<filter pattern="action.test.CheckBean.+" class="global.MyActionFilter2"/>
			<filter pattern="action.fake.*" class="global.MyActionFilter3"/>
			<filter pattern="action.test.UserAction" methods="(?!find|execute)\w*" class="global.UserActionFilter"/>
		-->
			<filter class="org.jessma.mvc.i18n.URLI18nFilter"/>
			<filter class="org.jessma.mvc.i18n.CookieI18nFilter"/>
			<!-- <filter class="org.jessma.mvc.i18n.BrowserI18nFilter"/> -->
			<filter pattern=".*" class="org.jessma.dao.DaoInjectFilter"/>
			<filter pattern=".*" class="org.jessma.ext.spring.SpringInjectFilter"/>
			<filter pattern=".*" class="guice.MyGuiceInjectFilter"/>
		</action-filters>
		
		<!-- 设置 Action Result 路径的全局别名 -->
		<result-path-aliases>
			<alias name="jsp-base" path="/jsp"/>
			<alias name="index" path="${jsp-base}/index.jsp"/>
			<alias name="jsp-path" path="${jsp-base}/test"/>
			<alias name="ftl-path" path="/ftl/test"/>
		</result-path-aliases>
		
		<global-results>
			<!-- MVC 框架会自动加入 'none' global result -->
			<!-- <result name="none" /> -->
		</global-results>
	</global>
	
	<include file="mvc-config-t.xml"/>
	
	<actions>
		<action name="index" class="action.test.IndexAction">
			<result>${index}</result>
		</action>
	</actions>
</MVC-MAIN>
