=== sioudhung/study/JessMA-master/support files/xsd/mvc-config-include-3.3.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://www.jessma.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	targetNamespace="http://www.jessma.org">
	<xs:element name="MVC-INCLUDE">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="include">
					<xs:complexType>
						<xs:attribute name="file" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="5" />
									<xs:pattern value=".+\.xml"></xs:pattern>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="actions">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="action">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="entry" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" minOccurs="0" name="result">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="name" default="success">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:pattern value="(\$|\#|\-|\_|\.|\w)+">
																				</xs:pattern>
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																	<xs:attribute name="type" default="dispatch">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:enumeration value="dispatch" />
																				<xs:enumeration value="redirect" />
																				<xs:enumeration value="chain" />
																				<xs:enumeration value="finish">
																				</xs:enumeration>
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="exception-mapping" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:attribute name="exception" default="java.lang.Exception">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:minLength value="1">
																		</xs:minLength>
																		<xs:pattern value="[a-z]\w*(\.([a-z]\w*))*\.[A-Z]\w*">
																		</xs:pattern>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="result" default="exception">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:pattern value="(\$|\#|\-|\_|\.|\w)+">
																		</xs:pattern>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" use="optional">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="0">
															</xs:minLength>
															<xs:pattern value="(\w+([-_.])?)*\w*">
															</xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="method">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1">
															</xs:minLength>
															<xs:pattern value="[a-z_$]+([\w_$])*">
															</xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element maxOccurs="unbounded" minOccurs="0" name="result">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="name" default="success">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:pattern value="(\$|\#|\-|\_|\.|\w)+">
																	</xs:pattern>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="type" default="dispatch">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="dispatch" />
																	<xs:enumeration value="redirect" />
																	<xs:enumeration value="chain" />
																	<xs:enumeration value="finish">
																	</xs:enumeration>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="exception-mapping" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute name="exception" default="java.lang.Exception">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1">
															</xs:minLength>
															<xs:pattern value="[a-z]\w*(\.([a-z]\w*))*\.[A-Z]\w*">
															</xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="result" default="exception">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="(\$|\#|\-|\_|\.|\w)+">
															</xs:pattern>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1" />
												<xs:pattern value="(\w+([-_.])?)*\w+">
												</xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="class">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1">
												</xs:minLength>
												<xs:pattern value="[a-z]\w*(\.([a-z]\w*))*\.[A-Z]\w*">
												</xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="path" default="/">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="(/((\w+([-/.])?)*\w+/?)?)?">
									</xs:pattern>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sioudhung/study/JessMA-master/support files/conf/mvc-config-t.xml
<?xml version="1.0" encoding="UTF-8"?>
<MVC-INCLUDE	xmlns="http://www.jessma.org"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation="http://www.jessma.org http://www.jessma.org/schema/mvc-config-include-3.3.xsd">
		
	<actions path="/test">
		<action name="testBean_1">
			<result>${jsp-path}/bean/test_bean_1.jsp</result>
		</action>
		<action name="checkBean_1" class="action.test.CheckBean1">
			<result>${jsp-path}/bean/result_1.jsp</result>
		</action>
		<action name="testBean_2">
			<result>${jsp-path}/bean/test_bean_2.jsp</result>
		</action>
		<action name="checkBean_2" class="action.test.CheckBean2">
			<result>${jsp-path}/bean/result_2.jsp</result>
		</action>
		<action name="testBean_3">
			<result>${jsp-path}/bean/test_bean_3.jsp</result>
		</action>
		<action name="checkBean_3" class="action.test.CheckBean3">
			<result>${jsp-path}/bean/result_3.jsp</result>
		</action>
		<action name="testBeanValidation">
			<result>${jsp-path}/bean/test_bean_vld.jsp</result>
		</action>
		<action name="testValidate">
			<result>${jsp-path}/validate/test_validate.jsp</result>
		</action>
		<action name="checkValidate" class="action.test.CheckValidate">
			<result>${jsp-path}/validate/result.jsp</result>
			<result name="input">${jsp-path}/validate/test_validate.jsp</result>
		</action>
		<action name="checkNickName" class="action.test.CheckNickName" />
		<action name="testI18N" class="action.test.ChangeLocale">
			<result>${jsp-path}/i18n/change_locale.jsp</result>
		</action>
		<action name="testI18N_Cookie" class="action.test.ChangeLocaleByCookie">
			<result>${jsp-path}/i18n/change_locale_cookie.jsp</result>
		</action>
		<action name="testUpload">
			<result>${jsp-path}/upload/test_upload.jsp</result>
		</action>
		<action name="checkUpload" class="action.test.CheckUpload">
			<result>${jsp-path}/upload/success.jsp</result>
			<result name="fail">${jsp-path}/upload/fail.jsp</result>
		</action>
		<action name="testDownload">
			<result>${jsp-path}/download/test_download.jsp</result>
		</action>
		<action name="checkDownload" class="action.test.CheckDownload">
		</action>
	</actions>
	
	<actions path="/test/dao">
		<action name="testJdbc">
			<result>${jsp-path}/dao/test_user_1.jsp</result>
		</action>
		<action name="createUser1" class="action.test.JdbcCreateUser">
			<result type="chain">./queryUser1</result>
		</action>
		<action name="queryUser1" class="action.test.JdbcQueryUser">
			<result>${jsp-path}/dao/test_user_1.jsp?fromQueryAction=true</result>
		</action>
		<action name="deleteUser1" class="action.test.JdbcDeleteUser">
			<result type="chain">./queryUser1</result>
		</action>
		<action name="testMyBatis">
			<result>${jsp-path}/dao/test_user_2.jsp</result>
		</action>
		<action name="createUser2" class="action.test.MyBatisCreateUser">
			<result type="chain">./queryUser2</result>
		</action>
		<action name="queryUser2" class="action.test.MyBatisQueryUser">
			<result>${jsp-path}/dao/test_user_2.jsp?fromQueryAction=true</result>
		</action>
		<action name="deleteUser2" class="action.test.MyBatisDeleteUser">
			<result type="chain">./queryUser2</result>
		</action>
		<action name="testHibernate">
			<result>${jsp-path}/dao/test_user_3.jsp</result>
		</action>
		<action name="createUser3" class="action.test.HibernateCreateUser">
			<result type="chain">./queryUser3</result>
		</action>
		<action name="queryUser3" class="action.test.HibernateQueryUser">
			<result>${jsp-path}/dao/test_user_3.jsp?fromQueryAction=true</result>
		</action>
		<action name="deleteUser3" class="action.test.HibernateDeleteUser">
			<result type="chain">./queryUser3</result>
		</action>
	</actions>
	
	<actions path="/test/page">
		<action name="queryInterest" class="action.test.QueryInterest">
			<result>${jsp-path}/static/test_query.jsp</result>
		</action>
	</actions>
	
	<actions path="/test/ftl">
		<action name="queryInterest" class="action.test.QueryInterest">
			<result>${ftl-path}/test_query.ftl</result>
		</action>
	</actions>
	
	<actions path="/test/entry">
		<!-- <action name="user" class="action.test.UserAction1"> -->
		<!-- <action name="user" class="action.test.UserAction2"> -->
		<!-- <action name="user" class="action.test.UserAction3"> -->
		<action name="user" class="action.test.UserAction">
			<entry name="create">
				<result type="chain">./user!query</result>
			</entry>
			<entry name="delete">
				<result type="chain">./user!query</result>
			</entry>
			<entry name="query" method="findUsers">
				<result>${jsp-path}/entry/test_user.jsp?fromQueryAction=true</result>
			</entry>
			<result>${jsp-path}/entry/test_user.jsp</result>
		</action>
	</actions>
	
	<actions path="/test/spring">
		<action name="user" class="action.test.SpringUserAction">
			<entry name="create">
				<result type="chain">./user!query</result>
			</entry>
			<entry name="delete">
				<result type="chain">./user!query</result>
			</entry>
			<entry name="query" method="findUsers">
				<result>${jsp-path}/spring/test_user.jsp?fromQueryAction=true</result>
			</entry>
			<result>${jsp-path}/spring/test_user.jsp</result>
		</action>	    
	</actions>
	
	<actions path="/test/guice">
		<action name="user" class="action.test.GuiceUserAction">
			<entry name="create">
				<result type="chain">./user!query</result>
			</entry>
			<entry name="delete">
				<result type="chain">./user!query</result>
			</entry>
			<entry name="query" method="findUsers">
				<result>${jsp-path}/guice/test_user.jsp?fromQueryAction=true</result>
			</entry>
			<result>${jsp-path}/guice/test_user.jsp</result>
		</action>	    
	</actions>
	
</MVC-INCLUDE>
