=== sioudhung/study/JessMA-master/support files/xsd/rest-config-3.3.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://www.jessma.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	targetNamespace="http://www.jessma.org">
	<xs:element name="REST">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" minOccurs="0" name="global">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="1" minOccurs="0" name="encoding">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="UTF-8">
										</xs:enumeration>
										<xs:enumeration value="GB2312">
										</xs:enumeration>
										<xs:enumeration value="GB18030">
										</xs:enumeration>
										<xs:enumeration value="GBK">
										</xs:enumeration>
										<xs:enumeration value="BIG5">
										</xs:enumeration>
										<xs:enumeration value="UTF-16">
										</xs:enumeration>
										<xs:enumeration value="UTF-16BE">
										</xs:enumeration>
										<xs:enumeration value="UTF-16LE">
										</xs:enumeration>
										<xs:enumeration value="ISO-8859-1">
										</xs:enumeration>
										<xs:enumeration value="US-ASCII">
										</xs:enumeration>
										<xs:enumeration value="">
										</xs:enumeration>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element maxOccurs="1" minOccurs="0" name="action-suffix">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="((\.)?([a-zA-Z0-9])+)?">
										</xs:pattern>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="rest-base-path" minOccurs="0" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="(/((\w+([-/.])?)*\w+/?)?)?">
										</xs:pattern>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="default-action-path" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="(/((\w+([-/.])?)*\w+/?)?)?">
										</xs:pattern>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="support-render-types" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="((\w+,? ?)*\w+)?">
										</xs:pattern>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="entities">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="entity">
								<xs:complexType>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:minLength value="1" />
												<xs:pattern value="(\w+([-_.])?)*\w+"></xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="action">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="([a-zA-Z][a-zA-Z0-9]*(-?[a-zA-Z0-9]+)*)?">
												</xs:pattern>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="action-path" default="/">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="(/((\w+([-/.])?)*\w+/?)?)?">
									</xs:pattern>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sioudhung/study/JessMA-master/support files/conf/rest-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<REST	xmlns="http://www.jessma.org"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.jessma.org http://www.jessma.org/schema/rest-config-3.3.xsd">
	<global>
		<!-- request 和 response 的默认编码（可选，默认：不设置） -->
		<encoding>UTF-8</encoding>
		<!-- Action 请求的后缀（可选，默认：'.action'） -->
		<action-suffix>.action</action-suffix>
		<!-- REST 请求的起始路径（可选，默认：'/'） -->
		<rest-base-path>/</rest-base-path>
		<!-- 默认 Action 路径（可选，默认：'/'） -->
		<default-action-path>/test/rest</default-action-path>
		<!-- 应用程序支持的视图类型（可选，默认：'html'） -->
		<!-- JessMA 3.2.1 支持 'html, xml, json' 三种类型 -->
		<!-- （注：第一个元素作为不带后缀名请求的默认视图类型） -->
		<support-render-types>html, xml, json</support-render-types>
	</global>

	<!-- REST 实体 user-2 映射到Action：/test/my-rest-2/my-user-2.action -->
	<entities action-path="/test/my-rest-2">
		<entity name="user-2" action="my-user-2"/>
	</entities>
	<entities action-path="/test/rest-3">
	</entities>
	<entities action-path="/test/async/">
		<entity name="test-rest"/>
	</entities>
</REST>
